import type { Metadata } from "next";
import { Geist, Geist_Mono, Raleway } from "next/font/google";
import "./globals.css";
import { createTables } from "@/lib/db";

//! criação das tabelas:
createTables();

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: '--font-raleway',
  subsets: ["latin"],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${raleway.variable}  antialiased`}
      >
        <div className="relative min-h-screen">

          <div className="absolute inset-0 bg-black/10 z-10 mx-auto"></div>

          <div className="relative z-20">
            {children} 
          </div>
        </div>
      </body>
    </html>
  );
}
